### ISSUE TITLE
Telecon: 11/25, 9:30 AM

### ISSUE THREAD

**Issue by arokem** [nrdg/afq-docs#15]
Link for the call: https://washington.zoom.us/j/710414359

Points for the agenda that I have are:

- [x]  Slides for the NIMH teleconference later same day (at: https://github.com/arokem/2019-11-25-BRAIN)
- [x] Continuous integration on pyAFQ :  Travis vs. GitHub Actions vs. ??? 

Please feel free to propose more points on this issue.

**Comment by jyeatman** [comment]
pyAFQ mAFQ comparison? Are we ready to run the data through pyAFQ and compare results?

**Comment by arokem** [comment]
Probably not before we implement https://github.com/yeatmanlab/pyAFQ/issues/168
