### ISSUE TITLE
Telecon February 7th,  2 PM PT

### ISSUE THREAD

**Issue by arokem** [nrdg/afq-docs#23]
@gkiar will tell us about his project that will use pyAFQ and we can discuss https://github.com/yeatmanlab/pyAFQ/pull/206

The link for the call is: https://washington.zoom.us/j/710414359

**Comment by gkiar** [comment]
A link to a very similar set of slides I'll be walking through can be [found on figshare](https://figshare.com/articles/Comparing_Perturbation_Models_for_Evaluating_Stability_of_Neuroimaging_Pipelines/10299212).

**Comment by arokem** [comment]
Adding to tomorrow's agenda to discuss whether we (I?) should submit something to present at the INCF conference: https://www.incf.org/blog/call-investigator-presentations-neuroinformatics-2020
